<?php
// Çoklu Dil Desteği

$lang = $_SESSION['lang'] ?? 'tr';

$translations = [
    'tr' => [
        // Genel
        'home' => 'Ana Sayfa',
        'listings' => 'İlanlar',
        'contact' => 'İletişim',
        'login' => 'Giriş Yap',
        'logout' => 'Çıkış',
        'admin_panel' => 'Admin Paneli',
        'search' => 'Ara',
        'filter' => 'Filtrele',
        'price' => 'Fiyat',
        'area' => 'Alan',
        'rooms' => 'Oda Sayısı',
        'bathrooms' => 'Banyo Sayısı',
        'details' => 'Detaylar',
        'offer' => 'Teklif Ver',
        'contact_us' => 'Bize Ulaşın',
        'submit' => 'Gönder',
        'cancel' => 'İptal',
        'save' => 'Kaydet',
        'delete' => 'Sil',
        'edit' => 'Düzenle',
        'add' => 'Ekle',
        'back' => 'Geri',
        'next' => 'İleri',
        'previous' => 'Önceki',
        'property_type' => 'Mülk Tipi',
        'all' => 'Tümü',
        'house' => 'Ev',
        'apartment' => 'Daire',
        'land' => 'Arsa',
        'tarla' => 'Tarla',
        'shop' => 'Dükkan',
        'villa' => 'Villa',
        'location' => 'Konum',
        'address' => 'Adres',
        'city' => 'Şehir',
        'district' => 'İlçe',
        'status' => 'Durum',
        'active' => 'Aktif',
        'sold' => 'Satıldı',
        'pending' => 'Beklemede',
        'offer_amount' => 'Teklif Tutarı',
        'your_name' => 'Adınız',
        'your_email' => 'E-posta',
        'your_phone' => 'Telefon',
        'message' => 'Mesaj',
        'property_details' => 'Mülk Detayları',
        'view_listing' => 'İlanı Görüntüle',
        'no_listings' => 'İlan bulunamadı',
        'currency' => 'TL',

        // Admin
        'admin_login' => 'Admin Girişi',
        'username' => 'Kullanıcı Adı',
        'password' => 'Şifre',
        'dashboard' => 'Panel',
        'manage_listings' => 'İlan Yönetimi',
        'manage_offers' => 'Teklif Yönetimi',
        'offers' => 'Teklifler',
        'new_listing' => 'Yeni İlan',
        'edit_listing' => 'İlan Düzenle',
        'offer_list' => 'Teklif Listesi',
        'customer_name' => 'Müşteri Adı',
        'customer_email' => 'Müşteri E-posta',
        'customer_phone' => 'Müşteri Telefon',
        'offer_status' => 'Teklif Durumu',
        'accept' => 'Kabul Et',
        'reject' => 'Reddet',
        'title' => 'Başlık',
        'description' => 'Açıklama',
        'images' => 'Resimler',
        'upload_image' => 'Resim Yükle',
        'login_error' => 'Kullanıcı adı veya şifre hatalı!',
        'login_success' => 'Başarıyla giriş yapıldı',
        'offer_sent' => 'Teklifiniz başarıyla gönderildi',
        'listing_added' => 'İlan başarıyla eklendi',
        'listing_updated' => 'İlan başarıyla güncellendi',
        'listing_deleted' => 'İlan başarıyla silindi',

        // Form labels
        'select_city' => 'Şehir Seçiniz',
        'select_district' => 'İlçe Seçiniz',
        'select_neighborhood' => 'Mahalle Seçiniz',
        'neighborhood' => 'Mahalle',
        'minimum_price' => 'Minimum Fiyat',
        'maximum_price' => 'Maksimum Fiyat',
        'minimum_area' => 'Minimum m²',
        'maximum_area' => 'Maksimum m²',
        'number_of_rooms' => 'Oda Sayısı',
        'number_of_bathrooms' => 'Banyo Sayısı',
        'desired_features' => 'İstediğiniz Özellikler',
        'additional_info' => 'Ek Bilgiler veya Notlar',
        'enter' => 'Giriniz',
        'all_types' => 'Tüm Türler',
        'all_locations' => 'Tüm Konumlar',

        // Listing Type
        'listing_type' => 'İlan Tipi',
        'for_sale' => 'Satılık',
        'for_rent' => 'Kiralık',
        'satilik' => 'Satılık',
        'kiralik' => 'Kiralık',
    ],
    'en' => [
        // General
        'home' => 'Home',
        'listings' => 'Listings',
        'contact' => 'Contact',
        'login' => 'Login',
        'logout' => 'Logout',
        'admin_panel' => 'Admin Panel',
        'search' => 'Search',
        'filter' => 'Filter',
        'price' => 'Price',
        'area' => 'Area',
        'rooms' => 'Rooms',
        'bathrooms' => 'Bathrooms',
        'details' => 'Details',
        'offer' => 'Make Offer',
        'contact_us' => 'Contact Us',
        'submit' => 'Submit',
        'cancel' => 'Cancel',
        'save' => 'Save',
        'delete' => 'Delete',
        'edit' => 'Edit',
        'add' => 'Add',
        'back' => 'Back',
        'next' => 'Next',
        'previous' => 'Previous',
        'property_type' => 'Property Type',
        'all' => 'All',
        'house' => 'House',
        'apartment' => 'Apartment',
        'land' => 'Land',
        'tarla' => 'Field',
        'shop' => 'Shop',
        'villa' => 'Villa',
        'location' => 'Location',
        'address' => 'Address',
        'city' => 'City',
        'district' => 'District',
        'status' => 'Status',
        'active' => 'Active',
        'sold' => 'Sold',
        'pending' => 'Pending',
        'offer_amount' => 'Offer Amount',
        'your_name' => 'Your Name',
        'your_email' => 'Email',
        'your_phone' => 'Phone',
        'message' => 'Message',
        'property_details' => 'Property Details',
        'view_listing' => 'View Listing',
        'no_listings' => 'No listings found',
        'currency' => 'TL',

        // Admin
        'admin_login' => 'Admin Login',
        'username' => 'Username',
        'password' => 'Password',
        'dashboard' => 'Dashboard',
        'manage_listings' => 'Manage Listings',
        'manage_offers' => 'Manage Offers',
        'offers' => 'Offers',
        'new_listing' => 'New Listing',
        'edit_listing' => 'Edit Listing',
        'offer_list' => 'Offer List',
        'customer_name' => 'Customer Name',
        'customer_email' => 'Customer Email',
        'customer_phone' => 'Customer Phone',
        'offer_status' => 'Offer Status',
        'accept' => 'Accept',
        'reject' => 'Reject',
        'title' => 'Title',
        'description' => 'Description',
        'images' => 'Images',
        'upload_image' => 'Upload Image',
        'login_error' => 'Invalid username or password!',
        'login_success' => 'Successfully logged in',
        'offer_sent' => 'Your offer has been sent successfully',
        'listing_added' => 'Listing added successfully',
        'listing_updated' => 'Listing updated successfully',
        'listing_deleted' => 'Listing deleted successfully',

        // Form labels
        'select_city' => 'Select City',
        'select_district' => 'Select District',
        'select_neighborhood' => 'Select Neighborhood',
        'neighborhood' => 'Neighborhood',
        'minimum_price' => 'Minimum Price',
        'maximum_price' => 'Maximum Price',
        'minimum_area' => 'Minimum m²',
        'maximum_area' => 'Maximum m²',
        'number_of_rooms' => 'Number of Rooms',
        'number_of_bathrooms' => 'Number of Bathrooms',
        'desired_features' => 'Desired Features',
        'additional_info' => 'Additional Information or Notes',
        'enter' => 'Enter',
        'all_types' => 'All Types',
        'all_locations' => 'All Locations',

        // Listing Type
        'listing_type' => 'Listing Type',
        'for_sale' => 'For Sale',
        'for_rent' => 'For Rent',
        'satilik' => 'For Sale',
        'kiralik' => 'For Rent',
    ]
];

function t($key)
{
    global $translations, $lang;
    return $translations[$lang][$key] ?? $key;
}
?>